export { default as Register } from "./Register";
export { default as POSRegister } from "./POSRegister";
export { default as POSBusinessInfo } from "./POSBusinessInfo";
export { default as SelectRegistrationType } from "./SelectRegistrationType";
export { default as POSVerification } from "./POSVerification";
export { default as BankRegister } from "./BankRegister";
export { default as BankDetails } from "./BankDetails";
export { default as BankVerification } from "./BankVerification";
export { default as AdminLogin } from "./AdminLogin";
